import Vue from "vue";
import { button } from "vant";
import { Swipe, SwipeItem } from "vant";
import { Collapse, CollapseItem } from "vant";
import { Search } from "vant";
import { Tab, Tabs } from "vant";
import { Form } from "vant";
import { Field } from "vant";
import { Toast } from "vant";
import { RadioGroup, Radio } from "vant";
import { Checkbox, CheckboxGroup } from "vant";
import { SwipeCell } from "vant";
import { Card } from "vant";

Vue.use(button);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Search);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Form);
Vue.use(Field);
Vue.use(Toast);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(SwipeCell);
Vue.use(Card);